# makefile for rectangle programs

app : program13-7.o rectangle.o
	g++ -o app program13-7.o rectangle.o

program13-7.o : program13-7.cpp
	g++ -c program13-7.cpp

rectangle.o : rectangle.cpp
	g++ -c rectangle.cpp
