# comments

# app : GradedActivity.o PassFailActivity.o PassFailExam.o program15-14.o
# 	g++ -o app GradedActivity.o PassFailActivity.o PassFailExam.o program15-14.o
#
# GradedActivity.o : GradedActivity.cpp
# 	g++ -c GradedActivity.cpp
#
# PassFailActivity.o : PassFailActivity.cpp
# 	g++ -c PassFailActivity.cpp
#
# PassFailExam.o : PassFailExam.cpp
# 	g++ -c PassFailExam.cpp
#
# program15-14.o : program15-14.cpp
# 	g++ -c program15-14.cpp

app2 : CsStudent.o program15-19.o
	g++ -o app2 CsStudent.o program15-19.o

CsStudent.o	: CsStudent.cpp
	g++ -c CsStudent.cpp

program15-19.o : program15-19.cpp
	g++ -c program15-19.cpp
