#makefile for pchallenges

app : pchallenge1.o date.o event.o
	g++ -o app pchallenge1.o date.o event.o

event.o : event.cpp
	g++ -c event.cpp

pchallenge1.o : pchallenge1.cpp
	g++ -c pchallenge1.cpp

date.o : date.cpp
	g++ -c date.cpp


